spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop
    properties.hibernate.temp.use_jdbc_metadata_defaults: false    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/bus
    username: postgres
    password: admin
    
server:
  port: 8090